import type { User, Collection } from "../types";

export const mockUsers: User[] = [
  {
    address: "NQ07 0000 0000 0000 0000 0000 0000 0000",
    name: "Nimiq Artist",
    avatar: "",
    bio: "Digital artist exploring the Nimiq ecosystem",
    joinedAt: "2023-01-15",
    followersCount: 1250,
    followingCount: 340,
    nftCount: 48,
    collectionCount: 3,
  },
  {
    address: "NQ07 1234 5678 9012 3456 7890 1234 5678",
    name: "Crypto Collector",
    avatar: "",
    bio: "Collector of rare digital assets on Nimiq",
    joinedAt: "2023-03-22",
    followersCount: 890,
    followingCount: 215,
    nftCount: 124,
    collectionCount: 1,
  },
  {
    address: "NQ07 ABCD EF01 2345 6789 ABCD EF01 2345",
    name: "Nimiq Builder",
    avatar: "",
    bio: "Building the future of NFTs on Nimiq",
    joinedAt: "2022-11-08",
    followersCount: 2100,
    followingCount: 180,
    nftCount: 72,
    collectionCount: 5,
  },
  {
    address: "NQ07 9876 5432 1098 7654 3210 9876 5432",
    name: "Digital Nomad",
    avatar: "",
    bio: "Traveling the digital world, one NFT at a time",
    joinedAt: "2023-06-01",
    followersCount: 560,
    followingCount: 420,
    nftCount: 35,
    collectionCount: 2,
  },
];

export const mockCollections: Collection[] = [
  {
    id: "col-001",
    name: "Nimiq Genesis",
    slug: "nimiq-genesis",
    description: "The original collection that started it all on Nimiq",
    image: "",
    bannerImage: "",
    creator: mockUsers[0],
    floorPrice: 150,
    totalVolume: 125000,
    totalItems: 1000,
    ownersCount: 342,
    createdAt: "2022-09-01",
    category: "art",
    featured: true,
  },
  {
    id: "col-002",
    name: "Nimiq Punks",
    slug: "nimiq-punks",
    description: "Unique pixel punk characters living on the Nimiq blockchain",
    image: "",
    bannerImage: "",
    creator: mockUsers[1],
    floorPrice: 80,
    totalVolume: 89000,
    totalItems: 5000,
    ownersCount: 1200,
    createdAt: "2023-01-10",
    category: "collectibles",
    featured: true,
  },
  {
    id: "col-003",
    name: "Nimiq Realms",
    slug: "nimiq-realms",
    description: "Explore fantastical realms and claim your digital territory",
    image: "",
    bannerImage: "",
    creator: mockUsers[2],
    floorPrice: 250,
    totalVolume: 210000,
    totalItems: 2500,
    ownersCount: 890,
    createdAt: "2022-12-15",
    category: "gaming",
    featured: true,
  },
  {
    id: "col-004",
    name: "Nimiq Beats",
    slug: "nimiq-beats",
    description: "Music NFTs from independent artists on Nimiq",
    image: "",
    bannerImage: "",
    creator: mockUsers[3],
    floorPrice: 60,
    totalVolume: 34000,
    totalItems: 800,
    ownersCount: 210,
    createdAt: "2023-04-20",
    category: "music",
    featured: false,
  },
  {
    id: "col-005",
    name: "Nimiq Lens",
    slug: "nimiq-lens",
    description: "Photography captured and preserved on the Nimiq blockchain",
    image: "",
    bannerImage: "",
    creator: mockUsers[0],
    floorPrice: 100,
    totalVolume: 56000,
    totalItems: 1200,
    ownersCount: 450,
    createdAt: "2023-02-28",
    category: "photography",
    featured: false,
  },
  {
    id: "col-006",
    name: "Nimiq Avatars",
    slug: "nimiq-avatars",
    description: "Your unique digital identity on Nimiq",
    image: "",
    bannerImage: "",
    creator: mockUsers[2],
    floorPrice: 120,
    totalVolume: 145000,
    totalItems: 10000,
    ownersCount: 2800,
    createdAt: "2022-10-05",
    category: "collectibles",
    featured: true,
  },
];
